import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "./_components/theme-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="rtsp-theme"
          >
            {/* a theme toggle at the top right  */}
            <div className="absolute top-2 right-2 p-4">
              <ModeToggle />
            </div>

            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
